apiVersion: apps/v1
#类型
kind: Deployment
#元数据
metadata:
  name: deployk8s
  #所属命名空间
  namespace: deployk8s
  labels:
    app: deployk8s
#详情
spec:
  #副本数量
  replicas: 1
  #保留历史版本，默认是10
  revisionHistoryLimit: 10
  paused: false
  #部署超时时间(s)
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: deployk8s
  template:
    metadata:
      labels:
        app: deployk8s
    spec:
      containers:
      - name: deployk8s
        image: 17060212119/deployk8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9900
---
apiVersion: v1
kind: Service
metadata:
  name: deployk8s
  namespace: deployk8s
  labels:
    app: deployk8s
spec:
  ports:
  - port: 9900
    protocol: TCP
    targetPort: 9900
  selector:
    app: deployk8s
  type: NodePort
